// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Helpers;

#nullable disable

namespace WebApi.Migrations.SqlServerMigrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApi.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });


            modelBuilder.Entity("WebApi.Entities.Leads", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                b.Property<string>("FirstName")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("LastName")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Suburb")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("DateCreated")
                    .HasColumnType("datetime");

                b.Property<string>("Suburb")
                  .HasColumnType("nvarchar(max)");

                b.Property<string>("Category")
                  .HasColumnType("nvarchar(max)");
                
                b.Property<string>("Description")
                  .HasColumnType("nvarchar(max)");

                b.Property<string>("Price")
                  .HasColumnType("decimal");

                b.Property<string>("Phone")
                  .HasColumnType("nvarchar(max)");

                b.Property<string>("Email")
                .HasColumnType("nvarchar(max)");

                  b.Property<string>("Status")
                  .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Leads");
            });

#pragma warning restore 612, 618
        }
    }
}
